version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hoteltonight
      MYSQL_USER: doron
      MYSQL_PASSWORD: password

  node:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-node
    links:
      - db
    ports:
      - "4000:4000"
    restart: always
    environment:
      PORT: 4000
      DB_PORT: 3306
      DB_HOST: db
      DB_PASSWORD: password
      DB_USER: root
      DB_NAME: hoteltonight
